[general]
n_steps = 1000
n_particles = 500
dt = 0.05

[initialization]

position_source_type = "random_hardsphere"  # Other option: file
init_seed = 7238659235

[physics]

dynamics_type = "brownian"  # Other options: rpy, stokesian
kT = 0.005305165 #
interaction_strength = 1. #in units of kBT
interaction_cutoff = 1.0
shear_rate = 1.0
shear_frequency = 1.0
friction_coefficient = 0.0
friction_range = 0.0
constant_force = [0.0, 0.0, 0.0]
constant_torque = [0.0, 0.0, 0.0]
buoyancy = false

[box]
Lx = 20
Ly = 20
Lz = 20
max_strain = 0.5

[seeds]
RFD = 43175675
ffwave = 6357442
ffreal = 6474524532
nf = 325425435

[output]

store_stresslet = false
store_velocity = false
store_orientation = false
writing_period = 20
thermal_fluctuation_test = "none"  # Other options: far-field, lubrication
