[general]

n_steps = 1000
n_particles = 1000
writing_period = 100

[physics]

dynamics_type = "brownian"  # Other options: rpy, stokesian
kT = 0.1
interaction_strength = 1.3
interaction_cutoff = 1.0
shear_rate = 1.0
shear_frequency = 1.0
friction_coeficient = 1.0
friction_range = 1.0


[box]
Lx = 10
Ly = 10
Lz = 10

[seeds]
initial_positions = 12039844
RFD = 1234
ffwave = 1239874
ffreal = 571023
nf = 38102399

[output]

store_stresslet = false
store_velocity = false
store_orientation = true

[input]


[constant_force]

fx = 1.0
fy = 0.0
fz = 0.0

[constant_torque]

fx = 1.0
fy = 0.0
fz = 0.0
